### ISSUE TITLE
Couldn't load plugin 'Pic2Map' - Qgis 3.14.16

### ISSUE THREAD

**Issue by fabiogiaco** [tproduit/pic2map#22]
Couldn't load plugin 'Pic2Map' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'piexif' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS 3.14/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/Fabio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Pic2Map\__init__.py", line 25, in classFactory
    from .pic2Map import Pic2Map
  File "C:/PROGRA~1/QGIS 3.14/apps/qgis/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Fabio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Pic2Map\pic2Map.py", line 24, in 
    from .getGCPMainWindow import GetGCPMainWindow
  File "C:/PROGRA~1/QGIS 3.14/apps/qgis/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Fabio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Pic2Map\getGCPMainWindow.py", line 36, in 
    from .posedialog import Pose_dialog
  File "C:/PROGRA~1/QGIS 3.14/apps/qgis/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Fabio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Pic2Map\posedialog.py", line 31, in 
    import piexif
  File "C:/PROGRA~1/QGIS 3.14/apps/qgis/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'piexif'

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.14.16-Pi Pi, df27394552 

Python Path:
C:/PROGRA~1/QGIS 3.14/apps/qgis/./python
C:/Users/Fabio/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Fabio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS 3.14/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS 3.14\apps\Python37
C:\PROGRA~1\QGIS 3.14\apps\Python37\Scripts
C:\Program Files\QGIS 3.14\bin\python37.zip
C:\PROGRA~1\QGIS 3.14\apps\Python37\DLLs
C:\PROGRA~1\QGIS 3.14\apps\Python37\lib
C:\Program Files\QGIS 3.14\bin
C:\PROGRA~1\QGIS 3.14\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS 3.14\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS 3.14\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS 3.14\apps\Python37\lib\site-packages\Pythonwin
C:/Users/Fabio/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Fabio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\joinmultiplelines
C:\Users\Fabio\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
C:/Users/Fabio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_resource_sharing
C:\Users\Fabio\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing
C:\Users\Fabio\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing\ext_libs
D:/data/Qgis_files

**Comment by MicheleTobias** [comment]
I had the same error with QGIS 3.20.0  I solved it by installing piexif (and then scipy because that was also missing) into my python 3.9 folder.  I followed the general procedure described in [this post](https://xl-optim.com/adding-python-packages-to-qgis-3-on-windows-10/).

**Comment by apiszcz** [comment]
Thank you.

**Comment by MicheleTobias** [comment]
I should probably note that in my error message, the folder it was looking for was Python39 and not Python37 like in the example above.
