### ISSUE TITLE
Uncaught ModuleNotFoundError: No module named 'OpenGL'


### ISSUE THREAD

**Issue by Detritalgeo** [tproduit/pic2map#6]
Couldn't load plugin 'Pic2Map' due to an error when calling its classFactory() method
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python\qgis\utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/MBodnar/AppData/Roaming/QGIS/QGIS3\profiles\Bodnar 2/python/plugins\Pic2Map\__init__.py", line 25, in classFactory
    from .pic2Map import Pic2Map
  File "C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python\qgis\utils.py", line 686, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/MBodnar/AppData/Roaming/QGIS/QGIS3\profiles\Bodnar 2/python/plugins\Pic2Map\pic2Map.py", line 23, in <module>
    from .buffers import Buffers
  File "C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python\qgis\utils.py", line 686, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/MBodnar/AppData/Roaming/QGIS/QGIS3\profiles\Bodnar 2/python/plugins\Pic2Map\buffers.py", line 16, in <module>
    from OpenGL.GL import *
  File "C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python\qgis\utils.py", line 686, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'OpenGL'

```
Pic2Map version 3.1, QGIS 3.6.3-Noosa on Windows 10

**Comment by tproduit** [comment]
You need to install OpenGL first. There is a small doc about that in the readme.
